sudo: required
services:
  - docker

before_install:
  - docker build -t paulomedeiros88/devradar-web:dev -f ./web/dev.Dockerfile ./web

script:
  - docker run -e CI=true paulomedeiros88/devradar-web:dev npm test

after_success:
  - docker build -t registry.heroku.com/devradar-app/backend ./backend
  - docker build -t registry.heroku.com/devradar-app/web ./web
  # Log in to the docker CLI
  - echo "$HEROKU_AUTH_TOKEN" | docker login -u "$HEROKU_DOCKER_USERNAME" --password-stdin registry.heroku.com
  # Take those images and push them to docker hub
  - docker push registry.heroku.com/devradar-app/backend
  - docker push registry.heroku.com/devradar-app/web