version: "3"
services:
  db:
    image: mongo:4.0.10-xenial
    volumes:
      - ./.mongodb:/data/db
    ports:
      - "27017:27017"
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      # - /app/node_modules
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "3333:3333"
  web:
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    volumes:
      # - /app/node_modules
      - ./web:/app
    depends_on:
      - backend
    ports:
      - "3000:3000"
