version: "3"
services:
  db:
    image: mongo:4.0.10-xenial
    volumes:
      - ./.mongodb:/data/db
    ports:
      - "27017:27017"
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    command: yarn debug
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    ports:
      - "3333:3333"
      - "9229:9229"
  web:
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    environment:
      - GRAPHQL_URL=http://localhost:3333/graphql
    volumes:
      - /app/node_modules
      - ./web:/app
    depends_on:
      - backend
    ports:
      - "3000:3000"
